train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: datasets/div2k/DIV2K_train_HR
      repeat: 20
      cache: in_memory
  wrapper:
    name: ope-sample-train
    args:
      inp_size: 48
      scale_min: 1
      scale_max: 4
      augment: true
      norm: true
      sample_q: 2304
  batch_size: 16

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./datasets/div2k/DIV2K_valid_HR
      first_k: 10
      repeat: 80
      cache: in_memory
  wrapper:
    name: ope-patch-eval
    args:
      inp_size: 48
      scale_factor: 4
      augment: true
      norm: true
  batch_size: 16


model:
  name: OPE-net-c
  args:
    max_freq: 3
    srnet_spec:
      name: adaptive-edsr-baseline
      args:
        n_feats: 147

optimizer:
  name: adam
  args:
    lr: 1.e-4

epoch_max: 1000

multi_step_lr:
  milestones: [200, 400, 600, 800]
  gamma: 0.5

epoch_val: 1
epoch_save: 5
resume: save/_train_edsr-OPE-abl-c_exp01/epoch-500.pth