train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: datasets/div2k/DIV2K_train_HR
      repeat: 20
      cache: in_memory
  wrapper:
    name: ope-sample-train
    args:
      inp_size: 48
      scale_min: 4
      scale_max: 8
      augment: true
      norm: true
      sample_q: 9216
  batch_size: 32

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./datasets/div2k/DIV2K_valid_HR
      first_k: 10
      repeat: 80
      cache: in_memory
  wrapper:
    name: ope-patch-eval
    args:
      inp_size: 48
      scale_factor: 4
      augment: true
      norm: true
  batch_size: 32


model:
  name: OPE-net
  args:
    max_freq: 3
    srnet_spec:
      name: swinir
      args:
        num_feat: 147

optimizer:
  name: adam
  args:
    lr: 2.e-4

epoch_max: 1000

multi_step_lr:
  milestones: [500, 800, 900, 950]
  gamma: 0.5

epoch_val: 1
epoch_save: 5